[theme]
name = "gruvbox-dark"
[icons]
name = "awesome5"
[icons.overrides]
music= "  "
cpu= "  "




[[block]]
block = "focused_window"
max_width = 50
show_marks = "all"

[[block]]
block = "music"
buttons = ["play"]



[[block]]
block = "cpu"
interval = 3

[[block]]
block = "networkmanager"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %r"
